import type { Episode } from "./types";

const defaultTranscript = [
  {
    time: 18,
    japanese: "でも、これは冬の夜に老人たちが語る話にすぎないだろう？",
    italian: "Ma queste sono solo storie vecchie. Tu pensi che siano vere?",
    grammar: "La particella でも introduce un contrasto morbido: ma, però.",
  },
  {
    time: 36,
    japanese: "分からない。祖父は理由もなく話を作る人ではなかった。",
    italian: "Non lo so. Mio nonno non inventava storie senza un motivo.",
    grammar: "ではなかった è la forma negativa passata e formale di だ.",
  },
  {
    time: 58,
    japanese: "しかし、今日の風は違う音がする。花に囁いているようだ。",
    italian: "Tuttavia, il vento oggi ha un suono diverso. Sembra che parli ai fiori.",
    grammar: "ようだ esprime apparenza o somiglianza: sembra che.",
  },
  {
    time: 82,
    japanese: "気をつけて。山は静かな時ほど危険なんだ。",
    italian: "Fa' attenzione. La montagna è più pericolosa proprio quando tace.",
    grammar: "ほど indica un grado proporzionale: tanto più... quanto più.",
  },
];

export const initialEpisodes: Episode[] = [
  {
    id: "time-girl",
    number: 1,
    title: "La ragazza che squarcia il tempo",
    series: "InuYasha",
    level: "N4",
    characters: ["Kagome", "Inuyasha"],
    image: "/images/source-2.jpg",
    status: "completed",
    progress: 100,
    duration: 24 * 60,
    updatedAt: "12 ottobre 2023",
    accuracy: 91,
    newKanji: 42,
    vocabulary: 118,
    transcript: defaultTranscript,
  },
  {
    id: "sphere-predators",
    number: 2,
    title: "I predatori della sfera",
    series: "InuYasha",
    level: "N4",
    characters: ["Lady Kaede"],
    image: "/images/source-3.jpg",
    status: "processing",
    progress: 65,
    duration: 23 * 60,
    updatedAt: "oggi, 14:30",
    accuracy: 0,
    newKanji: 0,
    vocabulary: 0,
    transcript: defaultTranscript,
  },
  {
    id: "black-hole",
    number: 3,
    title: "Ritorno dal buco nero",
    series: "InuYasha",
    level: "N3",
    characters: ["Sesshomaru"],
    image: "/images/source-4.jpg",
    status: "completed",
    progress: 100,
    duration: 25 * 60,
    updatedAt: "5 ottobre 2023",
    accuracy: 88,
    newKanji: 51,
    vocabulary: 126,
    transcript: defaultTranscript,
  },
  {
    id: "wind-whisper",
    number: 4,
    title: "Il sussurro del vento",
    series: "Mushishi S1",
    level: "N3",
    characters: ["Ginko"],
    image: "/images/source-9.jpg",
    status: "completed",
    progress: 100,
    duration: 24 * 60,
    updatedAt: "11 ottobre 2023",
    accuracy: 94,
    newKanji: 47,
    vocabulary: 132,
    transcript: defaultTranscript,
  },
];
